apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelines-as-code-demo
annotations:
  pipelinesascode.tekton.dev/task: "[git-clone]"
  pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
  pipelinesascode.tekton.dev/on-target-branch: "[master]"
spec:
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repo
        taskRef:
          - name: git-clone
        params:
          - name: url
            value: {{ repo_url }}
          - name: revision
            value: {{ revision }}
        workspaces:
          - name: output
            workspace: shared-workspace
      - name: build-from-source
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: maven
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: source
            workspace: shared-workspace